name: Build & Push (GHCR)
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: write
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set environment variables
        id: env
        run: |
          echo "PG_DSN=${{ secrets.PG_DSN }}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
  
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            PG_DSN=${{ env.PG_DSN }}
            OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}
          tags: |
            ghcr.io/quiby-ai/review-vectorizer:${{ github.sha }}
            ghcr.io/quiby-ai/review-vectorizer:main
          # optional: multiarch
          # platforms: linux/amd64,linux/arm64
